# Generated by Django 5.2.9 on 2025-12-31 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_rename_rooms_apartment_disposition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='apartments/'),
        ),
    ]
